### ISSUE TITLE
山东建投数据有限公司

### ISSUE THREAD

**Issue by zuojia** [QingDaoIT/BlackList#101]
2020年4-6月疫情期间，全员三个月连续扣20%工资，期间没有任何公示！后续向公司要这部分钱，最开始领导在群里保证肯定会补发（全员大群，有截图），后来电话也不接了，拉黑离职员工！去仲裁，公司竟然说这部分是扣的绩效!

**Comment by ls1141549077** [comment]
怎样,钱最后仲裁要回来了吗

**Comment by vvwcap** [comment]
现在公司加长烽数智科技有限公司，最近公司因为五险问题全公司降薪，公司多出的五险还得公司和个人一人一半，大大的避雷，以后不知道还会有什么问题
