### ISSUE TITLE
只要饿不死建议不要来这个公司

### ISSUE THREAD

**Issue by acmenorbartender** [QingDaoIT/BlackList#107]
简单描述一下这个公司，老板是一个五十多岁的大妈性格跟你在菜市场遇到的大妈差不多吧。你要是问我这种人为啥能开公司，两个字“关系”，剩下的自己理解吧。大妈去抢菜时候有多扣她就有多扣吧：大妈买菜多要几个塑料袋，她公司喝水用的热水壶是一个盖子坏了一半的某银行的赠送的壶（没有饮水器）。大妈觉得去哪家菜铺子买菜是菜铺子老板的荣幸，她觉得公司来公司工作都是员工的荣幸，所以恶心员工的事一件不拉（并且觉得折磨员工是对员工成长好，可能是看鸡汤文看多了这个理解咱们父母辈经常在微信上看着推送）。因为她本质上觉得工作是员工的命根子我再恶心你们你们也不走。说白了就是管理60后工人的理念。我觉得来这个公司唯一的好处就是让你明白一个道理，只要有关系傻逼都能开公司，尽管上的项目bug成灾。

**Comment by wkqnmdb-cnm** [comment]
1
