### ISSUE TITLE
青岛百百道信息科技有限公司/首德传媒

### ISSUE THREAD

**Issue by l981202ch** [QingDaoIT/BlackList#112]
刚离职 先占坑 以后再写

**Comment by suggeste** [comment]
去年离职的公司居然又让我刷到了哈哈哈, 疫情期间80%工资，一外包公司接不着活做自己的产品，傻逼需求一大堆，一拍脑门今天想出来明天就要要。后端进来非让人干全栈，把后端人弄走的时候嫌弃人后端的前端写的不好。也没给开全栈的钱啊。 钱少破事多，总想花小钱招人办大事。伺候不了

**Comment by suggeste** [comment]
每周一早晨需要提前半小时到公司开会，大冬天八点半也得早到半小时。开会也没正事就汇报上周工作叨叨打卡日报。 
一到下班点老板就到办公室坐着，啥也不干就坐那让你不好意思走。
下班时间正常休息日会各种破事找你
早晨还轮班打扫卫生 偶尔还得扛大桶水
你的计划永远赶不上老板的变化

**公司就那么几个人 等老板看到也能猜到我是谁  反正你在我印象里永远是个傻逼**
