### ISSUE TITLE
我正常要工资，说我是精神病 ，还要去新公司举报我，大家避雷（评论就是他本人）

### ISSUE THREAD

**Issue by july782** [QingDaoIT/BlackList#124]

**Comment by sdkeler** [comment]
工作态度极差，本身就是个心理有问题的员工，老觉得别人会破坏自己，该找医生看病了。 骚扰女同事，请发出证据，没证据的话，请不要乱说？ 据了解不是离职打的D把 ，前一个月就打的C，上级对员工进行考评，这个是正常现象，工作水平差，不从自身找原因，请不要无脑的发布这些言论，法治社会！

**Comment by sdkeler** [comment]
> 1老板性骚扰女同事，跟个疯子一样随便辱骂同事
> 2.背靠国企事业单位，其实跟国企事业单位一点关系都没有，比私企还不如，跟旧社会一样，老板甚至说“顺我者昌，逆我者亡这种话”
> 3.离职直接绩效打d，扣2000，问理由就是他愿意，不服找领导
> 4.因为不想被他骚扰，被他骂所以离职，之后就开始孤立我，
> 5.公司氛围及其不好，因为他带头养蛊，就希望大家斗得你死我活
工作态度极差，本身就是个心理有问题的员工，老觉得别人会破坏自己，该找医生看病了。 骚扰女同事，请发出证据，没证据的话，请不要乱说？ 据了解不是离职打的D把 ，前一个月就打的C，上级对员工进行考评，这个是正常现象，工作水平差，不从自身找原因，请不要无脑的发布这些言论，法治社会！

**Comment by sdkeler** [comment]
> 1老板性骚扰女同事，跟个疯子一样随便辱骂同事
> 2.背靠国企事业单位，其实跟国企事业单位一点关系都没有，比私企还不如，跟旧社会一样，老板甚至说“顺我者昌，逆我者亡这种话”
> 3.离职直接绩效打d，扣2000，问理由就是他愿意，不服找领导
> 4.因为不想被他骚扰，被他骂所以离职，之后就开始孤立我，
> 5.公司氛围及其不好，因为他带头养蛊，就希望大家斗得你死我活
需要我再次人肉出你的姓名，然后把这些发给你们现在的公司领导吗？法治社会，要讲证据，乱说话是要负责的，骚扰你有什么证据吗？ 再说骚扰你可以报案呀，就你说的这些，如果查出来你是谁，都可以告你诽谤了！

**Comment by july782** [comment]
> > 工作态度极差，本身就是个心理有问题的员工，老觉得别人会破坏自己，该找医生看病了。 骚扰女同事，请发出证据，没证据的话，请不要乱说？ 据了解不是离职打的D把 ，前一个月就打的C，上级对员工进行考评，这个是正常现象，工作水平差，不从自身找原因，请不要无脑的发布这些言论，法治社会！

**Comment by july782** [comment]
公司老板下场来威胁我

**Comment by july782** [comment]
无

**Comment by july782** [comment]
> 工作
