### ISSUE TITLE
无

### ISSUE THREAD

**Issue by july782** [QingDaoIT/BlackList#125]
无

**Comment by july782** [comment]
名称是缩写，因为全写的话他会搜索然后顺着网线来骂我，有需要的可以我可以发邮件回复
从业四年呆过最烂的公司，没有之一
1.让女员工陪酒唱歌
2.骂人非常厉害，做事跟土霸王一样，一到周六周末就开始在群里作妖，生怕大家过舒服了，整个公司氛围都搞的紧张兮兮
3.因为过于看不惯他，和他吵了一架，当月绩效打c扣1000，下个月离职直接打d扣2000，问原因就说没有理由，他就愿意，有本事找领导举报，正常讨论，直接把人拉黑，还到处造谣说我心理有问题

**Comment by bytebai920** [comment]
拼音搜不出来
