### ISSUE TITLE
山东圣点科技股份有限公司

### ISSUE THREAD

**Issue by Fake-Niddle** [QingDaoIT/BlackList#128]
1.硬的是关系户，流水般的同事，融入不进去努力工作的，会被称之为小团体。
2.现在开始玩拖欠工资了，之前晚发工资，会甩锅给银行，现在理由都懒得找了
3.面试一套，实际一套，说好的奖金、调薪，就当时放了个屁
4.算了，打字也挺累的

**Comment by zhenglaigang** [comment]
工资本来就压一个月，现在又快拖了两个月了；
相当于快三个月不发了；
最重点的是关系，外来的都是流水‘兄弟‘
