### ISSUE TITLE
青岛拓宇网络科技有限公司

### ISSUE THREAD

**Issue by ghost** [QingDaoIT/BlackList#187]
老板脑回路清奇，拿最近的事情来说，自己赚麻了买了大平层，刚装修好就要公司搬过去，导致很多员工身体不适依然不以为意。
奖金制度不透明，名义上以业绩多少计算，实际你们业绩一样拿到的钱也不一样，还是看老板心情。
技术部负责人既没有技术能力也没管理能力，全靠一张嘴，要求部门无效加班，即使没事情干也不能走做给老板看。

**Comment by shenchongshan** [comment]
你在这家公司了吗？我刚面试完呢，做市场的

**Comment by lzs5091** [comment]
我一直以为这是一家培训机构

**Comment by BBGhostX** [comment]
楼上说的技术部门负责人说的是那个什么阿蒙吧，确实感觉挺臭屁的，貌似他是老马的心腹，这都正常毛毛雨啦！ #

**Comment by BBGhostX** [comment]
唉唉！貌似这个公司出去的人没几个说好的。

**Comment by huchuansai** [comment]
拓宇还行其实
