### ISSUE TITLE
山东沐华医疗科技有限公司

### ISSUE THREAD

**Issue by zhudk** [QingDaoIT/BlackList#189]
1.各种培训洗脑，塑造老板英雄文化，灌输老板让员工跳楼，员工必须服从跳楼的企业文化；参加一次培训签一次6个月不能离职的条约；培训完要写感悟喝接下来怎么实践的承诺书。
2.公司8点半上班，8：25之前必须打卡，否则算迟到，说5分钟要用来进入工作状态！大小周
3.绩效考核每个月到要写6个价值观案例的小作文，技术和人事领导打分13分以上才及格，否则扣绩效；技术部哪里那么多客户第一，诚实守信的案例给你写，我上学也没每个月都得写纪实作文！
4.人事、产品强势，技术部领导弱势，话语权不足，一年至少要答辩写ppt3次以上，一群产品实习生指挥一群资深开发，也是服。
5.虚标薪资某直聘网站上标10-15，实际最高给到你10，妥妥的骗子，浪费面试者时间、感情，13薪也只有工资的1/4，说话不算数，做事能靠谱？
6.每年都可能会派你出去查体，派开发去乡镇查体，那条件无比简陋了，报销很抠，很繁琐。
7.老板不懂技术，也不看重技术，会拍者得天下啊。

**Comment by zhudk** [comment]
![企业微信截图_16570723461774](https://user-images.githubusercontent.com/14024612/177454269-f3f1e27f-6f83-46be-bf6a-4a5cf63e1873.png)

**Comment by phoenix12345** [comment]
我离开沐华也两年多了，当时我去的时候是单休，挺累的，不过没加过班；当时团队氛围很差：大家拉帮结派；成天有人在你 耳边说要离职（你tmd要离职赶紧滚，在我面前说个鸡巴，后来说要离职的人在这一直干，也没滚）。还是挺影响心情的。
再就是事多，我一个开发人员，成天参加人力的各种会议，我开发代码的时间被大大缩减了。还有一种激励机制，你拼命加班不给钱，给的是积分，哈哈。工资奇低，非常抠门，产品质量奇差。
喜欢用实习生，因为便宜，最坑爹的就是让你这个有经验的开发去带实习生。你想想，一大批菜狗实习生能做出个什么玩意？
定期洗脑，传播企业文化。。。你屁大个企业，玩什么文化？还不如投入精力去多干点正事

**Comment by ENAMCCC** [comment]
垃圾公司

**Comment by shuhen** [comment]
两年前去面试过，当时公司好像在一个不知道算小区还是办公性质的矮楼上，好像办公区没空调热烘烘的。老板似乎做移动医疗（类似早餐车）？吹得不小最后舍不得给待遇，幸亏没去。

**Comment by LeoHsi-code** [comment]
前2个月去面试过一次，给我留下了非常差的印象，大概说一下过程吧，公司在夏庄，大小周，位置很偏，由于我在市区住，所以boss上和HR确认过，如果能给到目标薪资，距离我是可以接受的，去了之后先填表，然后是技术面试，基本都回答上来了，技术面完之后让我在会议室等一下说还有一轮面试，等待期间我甚至都能清楚地听到他们在会议室外质问HR为什么要让人来面试，大概20分钟后，进来俩人，一男（技术？）一女（行政），进来之后也不解释为什么让我等了20分钟，俩人一唱一和开始贬低我，要是不想招人就别TM浪费大家时间，这种垃圾公司大家不用考虑了，不值得

**Comment by xssed** [comment]
> 前2个月去面试过一次，给我留下了非常差的印象，大概说一下过程吧，公司在夏庄，大小周，位置很偏，由于我在市区住，所以boss上和HR确认过，如果能给到目标薪资，距离我是可以接受的，去了之后先填表，然后是技术面试，基本都回答上来了，技术面完之后让我在会议室等一下说还有一轮面试，等待期间我甚至都能清楚地听到他们在会议室外质问HR为什么要让人来面试，大概20分钟后，进来俩人，一男（技术？）一女（行政），进来之后也不解释为什么让我等了20分钟，俩人一唱一和开始贬低我，要是不想招人就别TM浪费大家时间，这种垃圾公司大家不用考虑了，不值得

感觉把办公室定在那么便宜的地方本身也没什么实力。

**Comment by zhudk** [comment]
> 

哈哈那个女的可烦人了

**Comment by ghost** [comment]
本人也去面试过。说一下了解到的公司问题，大小周，加班是常态。忘记说加班有没有工资还是调休来着，去面试的时候，让我自己在会议室等了半个小时，emmm，要是没有时间可以提前说。面试的问题还好，技术也不像什么大佬

**Comment by Daydreamer-zz** [comment]
老板是个傻逼罢了，前几天去面试，妈的进门还TMD递名片，装什么，办公的地方是真乱
我在会议室一直等，面完一个还有一个，一共4个，真TM服了，整整一个下午，真TM浪费时间

**Comment by SaikiLin** [comment]
经历类似，青岛沐华医疗，和这个是一家，避坑，希望大家能多告诉身边的人，不能让这垃圾公司坑害更多的人

**Comment by SaikiLin** [comment]
经历类似，青岛沐华医疗，和这个是一家，避坑，希望大家能多告诉身边的人，不能让这垃圾公司坑害更多的人。再加一条公司某s姓领导的名句
`“如果你五点半准点下班了，那就证明你至少提前半个小时到一个小时，工作就做完了”`
`“公司给你培训是让你成长的，你居然好意思问我要加班费”`
“试用期加班，不算加班，没有加班费”

**Comment by PenguinBully** [comment]
> 经历类似，青岛沐华医疗，和这个是一家，避坑，希望大家能多告诉身边的人，不能让这垃圾公司坑害更多的人。再加一条公司某s姓领导的名句 “试用期加班，不算加班，没有加班费”`“如果你五点半准点下班了，那就证明你至少提前半个小时到一个小时，工作就做完了”``“公司给你培训是让你成长的，你居然好意思问我要加班费”`

是姓石还是姓孙，哈哈哈哈哈

**Comment by SaikiLin** [comment]
> 

当然是石大领导啦，邵大代表把他驯服的不错，很听话

**Comment by SaikiLin** [comment]
当然是石大领导啦，邵大代表把他驯服的不错，很听话


PenguinBully ***@***.***> 于2023年8月23日周三 13:15写道：

**Comment by qq845911445** [comment]
哈哈 昨天去面试 情况和你的基本一样

**Comment by qq845911445** [comment]
> 前2个月去面试过一次，给我留下了非常差的印象，大概说一下过程吧，公司在夏庄，大小周，位置很偏，由于我在市区住，所以boss上和HR确认过，如果能给到目标薪资，距离我是可以接受的，去了之后先填表，然后是技术面试，基本都回答上来了，技术面完之后让我在会议室等一下说还有一轮面试，等待期间我甚至都能清楚地听到他们在会议室外质问HR为什么要让人来面试，大概20分钟后，进来俩人，一男（技术？）一女（行政），进来之后也不解释为什么让我等了20分钟，俩人一唱一和开始贬低我，要是不想招人就别TM浪费大家时间，这种垃圾公司大家不用考虑了，不值得

我也是，前几天刚面试完，进去感觉工作环境很差，整个屋子不透光，闷闷的，进去先填表等等，第一轮就等了十分钟，第二轮等了得有20分钟吧，第二轮也是一男一女？情况是一模一样，无语

**Comment by iiZeke** [comment]
> 前2个月去面试过一次，给我留下了非常差的印象，大概说一下过程吧，公司在夏庄，大小周，位置很偏，由于我在市区住，所以boss上和HR确认过，如果能给到目标薪资，距离我是可以接受的，去了之后先填表，然后是技术面试，基本都回答上来了，技术面完之后让我在会议室等一下说还有一轮面试，等待期间我甚至都能清楚地听到他们在会议室外质问HR为什么要让人来面试，大概20分钟后，进来俩人，一男（技术？）一女（行政），进来之后也不解释为什么让我等了20分钟，俩人一唱一和开始贬低我，要是不想招人就别TM浪费大家时间，这种垃圾公司大家不用考虑了，不值得

我也是，前几天刚面试完，进去感觉工作环境很差，整个屋子不透光，闷闷的，进去先填表等等，第一轮就等了十分钟，第二轮等了得有20分钟吧，第二轮也是一男一女？情况是一模一样，无语

**Comment by iiZeke** [comment]
> 前2个月去面试过一次，给我留下了非常差的印象，大概说一下过程吧，公司在夏庄，大小周，位置很偏，由于我在市区住，所以boss上和HR确认过，如果能给到目标薪资，距离我是可以接受的，去了之后先填表，然后是技术面试，基本都回答上来了，技术面完之后让我在会议室等一下说还有一轮面试，等待期间我甚至都能清楚地听到他们在会议室外质问HR为什么要让人来面试，大概20分钟后，进来俩人，一男（技术？）一女（行政），进来之后也不解释为什么让我等了20分钟，俩人一唱一和开始贬低我，要是不想招人就别TM浪费大家时间，这种垃圾公司大家不用考虑了，不值得

我也是，前几天刚面试完，进去感觉工作环境很差，整个屋子不透光，闷闷的，进去先填表等等，第一轮就等了十分钟，第二轮等了得有20分钟吧，第二轮也是一男一女，情况是一模一样，无语
