### ISSUE TITLE
问下优诺口腔这公司的开发怎么样？

### ISSUE THREAD

**Issue by ayachaim** [QingDaoIT/BlackList#258]

**Comment by MingA21** [comment]
哪家公司要求 研发穿正装、 哪家公司节假日不休息

**Comment by ayachaim** [comment]
> 哪家公司要求 研发穿正装、 哪家公司节假日不休息

老哥展开说说，加班很多吗？开发规范吗

**Comment by forceChange** [comment]
> 哪家公司要求 研发穿正装、 哪家公司节假日不休息老哥老哥，细细说说呀，坑不坑啊

**Comment by ayachaim** [comment]
> 哪家公司要求 研发穿正装、 哪家公司节假日不休息

老哥，细细说说呀，坑不坑啊
