### ISSUE TITLE
黑名单信息

### ISSUE THREAD

**Issue by ghost** [QingDaoIT/BlackList#285]
关闭评论

**Comment by johnZhO** [comment]
安工院属于青岛央企天花板了。但你这是外包，干外包都一样，哪都不太行。

**Comment by yg-92** [comment]
首先对你的遭遇表示同情，其次对于你对低学历或培训班出身开发者的偏见并不赞同。

**Comment by gospelsnake** [comment]
了解过一段时间，天花板不至于。石化下面的三级公司都不止了吧。好点的国企无外乎就是七险二金。全部顶格缴纳，据我所知这企业好像还没到七险二金这个档次吧。。公司也没几个人。能有100个？？好像是做石化业危险源大数据智能检测的。。。只能说楼主以后看清楚点，别去外包了。没前途的。。。

**Comment by HuXin96** [comment]
@johnZhO @yg-92 您俩可别装了，还以为认不出来你们俩？？我都指名道姓说你俩，脸皮可真够厚的，还天花板，笑死。就跟这辈子我没见过国企？？？

**Comment by HuXin96** [comment]
@yg-92 杨总如今现在越来越会拉腔了，现在系统出这么大的问题，您老把锅甩给外包合适吗？就算开了所有的外包也阻挡不了安工数联现在就是不行了，业务不行，内部内斗，找了个二流子给你写代码，我觉得这钱你还不如找个外包企业包出去

**Comment by yg-92** [comment]
> @yg-92 杨总如今现在越来越会拉腔了，现在系统出这么大的问题，您老把锅甩给外包合适吗？就算开了所有的外包也阻挡不了安工数联现在就是不行了，业务不行，内部内斗，找了个二流子给你写代码，我觉得这钱你还不如找个外包企业包出去

我倒是真的希望自己是个领导，建议你抽空去眼科医院挂个号吧
