### ISSUE TITLE
青岛脚印信息技术有限公司

### ISSUE THREAD

**Issue by 744934982** [QingDaoIT/BlackList#37]

**Comment by kfkfifisii** [comment]
我也写个真实的试试：
1.有一说一，拖欠工资确实是常态，这边是20发工资，在职期间最多拖欠三个月工资，适逢年假期间，提前2-3天放假顺延2天上班的情况下，在员工全部未知的情况下把这几天工资全部扣除，每个人工资基本砍掉接近一半，导致第一次离职潮，技术员工离职超过半数之多。
2.基本是先最赶工做项目，再谈合同经常做完了 或者做了一半的项目流产，工期信口开河，只负责谈从不管是否合理，真的喜欢花大饼，19年初还考试加薪，考题就是老板许下的承诺公司今年目标和实施规划步骤啥的：‘一年盈利1500万，工资拿出来500万，年终奖6个月工资！’
3.空降过一个纸上谈兵情商堪忧的啥啥啥硕士，也忘了，口头禅：‘你肯定代码有问题，谁写的谁交付’，高薪聘请（比程序员工资高）测试：一个bug扣多少钱忘了，奖励测试多钱忘记了。。。不发工资 还要以这种高压姿态来以测试压开发？程序员是否下班要经过测试批准检查作业，早上开会分配任务！告诉我执行的驱动力是啥啊！能执行下去么？不知道现在是否执行了。
4.管理者也挺盲目的瞎搞一通，之前一个说多牛多牛一直夸，结果一个小项目做不完离职了也不吹了。现在还有一个一样的情况 只要老板认准了脸就是打肿了也得挺着认同，不管做的对不对，面子最重要！
5.最后一条没啥说的很多公司也都这样吧，离职扣钱，把工资拆分了。扣绩效等等。这个没啥吐槽的，我就是要走，不给我都走。因为过年乱扣工资还吃过官司，上班后还然我们签字 拟了一份员工手册也不知道啥的 开会的都要签名，就是不上班的时间扣钱正常，当时在公司也签了。
6.我补充一个哈哈哈，那就是程序员卖蘑菇！老板从甘肃弄来的，在李村大集一个仓库，一群程序员装蘑菇，包装蘑菇，运输蘑菇，卖蘑菇哈哈哈！大冬天的 在个破仓库又累又冷的，往乐客城运输到半夜！想想就窝火！
