### ISSUE TITLE
青岛投道网络科技发展有限公司

### ISSUE THREAD

**Issue by QingDaoIT** [QingDaoIT/BlackList#6]

**Comment by QingDaoIT** [comment]
关于工资计算方式的通知
1.年前1.24-1.31的，按照每个人的工资一周占一个月的比例 +10%发
2.年后的从2.12开始算，以后都是计算本月12号到下个月11号，每月20号发工资
3.本月先发各自工资的一半，3月11号计算完再发剩下的
4.明天要把2.12 - 2.27 的项目进度计算出来

有什么问题明天开个小会讨论一下

**Comment by yunhaiyidao** [comment]
加班到12点，老板会耍小心眼，如果不加班到12点一个月2000，天天各种眼色批斗

**Comment by yunhaiyidao** [comment]
垃圾中的战斗机，一个个菜如狗，外包嘛，除了加班，什么也学不到

**Comment by dafaWang** [comment]
boss上感觉还不错。。没想到这么坑啊

**Comment by love0304** [comment]
sad

**Comment by love0304** [comment]
入职不签正常合同， 签试用期合同，试用期合同各种坑。     就说其中有一条： 工作不满一个自然月，前俩个周没工资 ，基本上会在不满一个月自然月前找理由把你辞退，然后不发前俩周工资。

**Comment by xushenjie** [comment]
有幸呆过，垃圾外包公司，有时候没活，就发个基本工资，还特么qq转账，老板典型忽悠，加班严重，不加班会找你事，内部政治严重，离职率相当高。记得最明智的是当时让员工入股接的外包项目，全公司就我跟另一个没扔钱

**Comment by conanmiao** [comment]
> 加班到12点，老板会耍小心眼，如果不加班到12点一个月2000，天天各种眼色批斗

请问你说“加班不到12点就给2000”，你能拿出证据么？公司技术薪资是使用职级制度，不同职级对应的薪资都是公开透明的，现在公司接近五十人，目前在当地已经是颇具规模的软件公司了，有必要因为某个人加班时间不够，就发2000工资？我觉得只要稍微有点独立思考能力，也能看出来这个是属于恶意攻击的。我目前是在职员工，可以以人格担保，公司没有强制要求过任何人加班，公司的氛围和文化很优秀。投道从五六个人个人，发展到现在四十多个人，就用了三年多的时间，目前已是黄岛最大规模的和最有品牌的软件外包类公司，真的是有它的道理的，这离不开公司文化，离不开每个小伙伴的努力和认可，而且前景也很明朗。我自己可以拍着胸脯的说，投道是一家非常优秀的公司，敢于接受社会的监督和检查，所以请管理员给与公正处理。

**Comment by conanmiao** [comment]
> 垃圾中的战斗机，一个个菜如狗，外包嘛，除了加班，什么也学不到

你这评论是恶意攻击。你说别人菜如狗，那你技术是大神了？你要是技术大神，你还要求学什么东西？你只需要像现在这样“指点江山、到处乱喷”就可以了。
说到加班，公司没有强制要求过任何人加班，注意是“要求员工加班”。有员工加班，也是因为员工对于自己负责的项目和技术有责任心，能够站在公司的高度去看待问题，难道这不是员工得到技术提升和职级晋升很好的方式吗？要不要加班，这个完全取决于自己，目前公司有每天到点就下班的小伙伴，也有主动加班到10点的小伙伴，也有下班不走留在公司学习的小伙伴。每个人对自己的职业规划和认知不同，付出的努力不同，也决定了每个人的成长和发展不同。这个没有必要对加班这件事这么嫉恶如仇吧。再说了，一个软件类公司如果从来不加班，到点就没人了（我以前经历过这样的公司，这也是我离开的原因），也可想而知这家公司的战斗力和竞争力了会多么懈怠了。
一个公司好不好，看的是氛围和文化，看的是是否能够带动大家一起发展和成长，看的是能否带动大家能够愿意和公司一起打拼一份事业，而不是看是不是从不加班。

**Comment by yunhaiyidao** [comment]
“你能证明你就是你自己吗？你能证明我偷的那本书就是你的吗，你让书开口说话啊”，孔乙己看了一下那条被人打残的右腿，心里不由的想起来隔壁家 阿Q告诉他吴妈、假洋鬼子、王胡、小D的故事。心里一下子有了底气，抿了抿嘴边的唾沫，开始胡思乱想起来

**Comment by conanmiao** [comment]
> 入职不签正常合同， 签试用期合同，试用期合同各种坑。 就说其中有一条： 工作不满一个自然月，前俩个周没工资 ，基本上会在不满一个月自然月前找理由把你辞退，然后不发前俩周工资。

你是在开玩笑？
“前两周没工资”，这个事从来没有过，
“不满一个月就找理由把人辞退”，公司框架和项目还没熟悉呢，就把人辞掉，那公司图个啥？一个项目要是依靠频繁换人的方式来开发，那成本大了去了，几乎要每个月重构一次，我想不会有哪个公司傻到采用这种战术来做项目吧？

**Comment by yunhaiyidao** [comment]
三年过去了，欠我的一个月工资，到现在还没还

**Comment by yunhaiyidao** [comment]
> > 垃圾中的战斗机，一个个菜如狗，外包嘛，除了加班，什么也学不到
> 
> 你这评论是恶意攻击。你说别人菜如狗，那你技术是大神了？你要是技术大神，你还要求学什么东西？你只需要像现在这样“指点江山、到处乱喷”就可以了。
> 说到加班，公司没有强制要求过任何人加班，注意是“要求员工加班”。有员工加班，也是因为员工对于自己负责的项目和技术有责任心，能够站在公司的高度去看待问题，难道这不是员工得到技术提升和职级晋升很好的方式吗？要不要加班，这个完全取决于自己，目前公司有每天到点就下班的小伙伴，也有主动加班到10点的小伙伴，也有下班不走留在公司学习的小伙伴。每个人对自己的职业规划和认知不同，付出的努力不同，也决定了每个人的成长和发展不同。这个没有必要对加班这件事这么嫉恶如仇吧。再说了，一个软件类公司如果从来不加班，到点就没人了（我以前经历过这样的公司，这也是我离开的原因），也可想而知这家公司的战斗力和竞争力了会多么懈怠了。
> 一个公司好不好，看的是氛围和文化，看的是是否能够带动大家一起发展和成长，看的是能否带动大家能够愿意和公司一起打拼一份事业，而不是看是不是从不加班。

因为公司不加班，你离开了公司！哈哈哈哈，这么有理想的员工，我也想要，来芒果数据分析搞兼职，一个月轻松2~3万，我看你在他这个公司，应该超不过2万，就算加班到25点

**Comment by 1018103730** [comment]
> > 加班到12点，老板会耍小心眼，如果不加班到12点一个月2000，天天各种眼色批斗
> 
> 请问你说“加班不到12点就给2000”，你能拿出证据么？公司技术薪资是使用职级制度，不同职级对应的薪资都是公开透明的，现在公司接近五十人，目前在当地已经是颇具规模的软件公司了，有必要因为某个人加班时间不够，就发2000工资？我觉得只要稍微有点独立思考能力，也能看出来这个是属于恶意攻击的。我目前是在职员工，可以以人格担保，公司没有强制要求过任何人加班，公司的氛围和文化很优秀。投道从五六个人个人，发展到现在四十多个人，就用了三年多的时间，目前已是黄岛最大规模的和最有品牌的软件外包类公司，真的是有它的道理的，这离不开公司文化，离不开每个小伙伴的努力和认可，而且前景也很明朗。我自己可以拍着胸脯的说，投道是一家非常优秀的公司，敢于接受社会的监督和检查，所以请管理员给与公正处理。


> ，老板会耍小心眼，如果不加班到12点一个月2000，天天各种眼

这彩虹屁真香啊~

**Comment by 1018103730** [comment]
> > 加班到12点，老板会耍小心眼，如果不加班到12点一个月2000，天天各种眼色批斗
> 
> 请问你说“加班不到12点就给2000”，你能拿出证据么？公司技术薪资是使用职级制度，不同职级对应的薪资都是公开透明的，现在公司接近五十人，目前在当地已经是颇具规模的软件公司了，有必要因为某个人加班时间不够，就发2000工资？我觉得只要稍微有点独立思考能力，也能看出来这个是属于恶意攻击的。我目前是在职员工，可以以人格担保，公司没有强制要求过任何人加班，公司的氛围和文化很优秀。投道从五六个人个人，发展到现在四十多个人，就用了三年多的时间，目前已是黄岛最大规模的和最有品牌的软件外包类公司，真的是有它的道理的，这离不开公司文化，离不开每个小伙伴的努力和认可，而且前景也很明朗。我自己可以拍着胸脯的说，投道是一家非常优秀的公司，敢于接受社会的监督和检查，所以请管理员给与公正处理。



> > 加班到12点，老板会耍小心眼，如果不加班到12点一个月2000，天天各种眼色批斗
> 
> 请问你说“加班不到12点就给2000”，你能拿出证据么？公司技术薪资是使用职级制度，不同职级对应的薪资都是公开透明的，现在公司接近五十人，目前在当地已经是颇具规模的软件公司了，有必要因为某个人加班时间不够，就发2000工资？我觉得只要稍微有点独立思考能力，也能看出来这个是属于恶意攻击的。我目前是在职员工，可以以人格担保，公司没有强制要求过任何人加班，公司的氛围和文化很优秀。投道从五六个人个人，发展到现在四十多个人，就用了三年多的时间，目前已是黄岛最大规模的和最有品牌的软件外包类公司，真的是有它的道理的，这离不开公司文化，离不开每个小伙伴的努力和认可，而且前景也很明朗。我自己可以拍着胸脯的说，投道是一家非常优秀的公司，敢于接受社会的监督和检查，所以请管理员给与公正处理。

>> 这彩虹屁 受不了~
