### ISSUE TITLE
之前的一些公司的有的关闭了什么意思？

### ISSUE THREAD

**Issue by owen77788** [QingDaoIT/BlackList#65]
之前的几个公司的黑历史被关闭什么意思，花钱删评论？

**Comment by dishci** [comment]
为所欲为

**Comment by QingDaoIT** [comment]
可以附带证据  重新提交。

**Comment by owen77788** [comment]
重新提交了还有什么意思？本来就是好几个人的经历，我就想知道谁删的？

**Comment by QingDaoIT** [comment]
你说的是哪个公司？管理只关闭青岛投道科技有限公司，是因为公司联系到了当事人，当事人删除评论后管理关闭。

**Comment by owen77788** [comment]
优秀没事了，这样的黑名单还能保护咱们这些工作者吗
