### ISSUE TITLE
青岛铭数科技

### ISSUE THREAD

**Issue by Qing-sq** [QingDaoIT/BlackList#69]

**Comment by Qing-sq** [comment]
后台接口500是你的错，后台接口规范不对是因为你让后台改规范，去问后台，后台一脸懵逼。为了提现你的项目有多烂，她自己多好，晚上加班疯狂push代码，修改下宽度提一次代码，把修改新增一个页面改成俩页面push一次代码。因为试用期六个月，不管你在公司多久了，劝退你也是想让你当场走，你不提就直接让你当天办手续走人。已经劝退好几个了，美其名曰又为公司省了钱

**Comment by ElvistLui** [comment]
就是这一个领导的问题么？还是其他领导也这样？

**Comment by qdcrazyabout** [comment]
负责人叫周琦，超级水。。而且贼能比比。入职之后，缩着就行了，千万别表现出来。。那就是个二傻子。。

**Comment by warmer1914** [comment]
> 负责人叫周琦，超级水。。而且贼能比比。入职之后，缩着就行了，千万别表现出来。。那就是个二傻子。。

这名字一看就水啊 波兰选手 哈哈
