### ISSUE TITLE
青岛贝塔信息技术有限公司

### ISSUE THREAD

**Issue by yasuoyo** [QingDaoIT/BlackList#75]
外包公司 长期出差驻厂开发

**Comment by Good-XiaAo** [comment]
> 外包公司 长期出差驻厂开发

感觉这种也没什么坑，这种也没必要报黑名单了吧

**Comment by 27yianjie** [comment]
> > 外包公司 长期出差驻厂开发
> 
> 感觉这种也没什么坑，这种也没必要报黑名单了吧

长期不发工资，项目款要不回来(ps:无能boss)，时不时还PUA一下，最关键是压力的受不了
