### ISSUE TITLE
金鸢信息科技(青岛)有限公司

### ISSUE THREAD

**Issue by QdBatman** [QingDaoIT/BlackList#79]
1、入职不签合同，说小公司没这么多讲究
2、转正也不签合同，并且转正也不缴纳五险一金
3、公司就是在城阳天安数码城租了两个工位

**Comment by QdBatman** [comment]
补充：
4、发放工资不及时，还得跟后边要才能拖一周发放

**Comment by shyboylpf** [comment]
不签合同可是双倍工资 , 仲裁就完了
