### ISSUE TITLE
青岛中兴盛智能科技有限公司

### ISSUE THREAD

**Issue by InMyLife888** [QingDaoIT/BlackList#98]
1、这个公司来容易，想走难上加难，离职各种刁难
2、转正难，来之前说的3个月试用期，到时间各种理由拒绝转正
3、平时各种项目就没有不急的，天天催，就想让你无偿加班
4、老板天天画饼，说每个月聚餐一次，几个月了都没聚，说换办公场地，几个月了都没换
5、平时请假都不忘记问候你，让你在家干活
6、每天写日报，日报写太短了让你写详细，一句话就能说明白的非得扯10句话，写详细就算了，竟然能问出来你做的是哪个项目
7、老板对业务、需求啥也不懂，看项目瞎指挥

**Comment by ghost** [comment]
本楼层不定时更新
1.只签一份合同，合同到期时间不写，说和老板商量一下再写，然后就没后话了
2.老板不懂开发，控制欲贼强，整天画饼，说每月开一次总结会，表彰优秀员工，发项目奖金，评选季度优秀员工，会有公费旅游之类的奖励，结果半年了就发了一次奖金（200RMB）
3.公司位置在居民楼，两室一厅，房租到期2月了一直没交，房东都来公司催了，老板一直说搬去办公楼，说了小半年了也没搬
4.试用期为3个月，但是满3个月的时候不会主动找你，得你去问，然后写转正申请，然后就没信了，得等你再主动问，会说老板忙没回复之类的，大约催个两三次就有结果了。不是个例，基本都是这么个情况
5.项目很多，很急，一问周期项目经理就说催的很急，抓紧做，往下干，做不完加加班，基本一两周一个项目
6.加班没餐补，没加班费，没调休，不管饭（买过几次泡面，项目经理自掏腰包订过几次饭），打车倒是报销
7.离职难，老板项目经理之间踢皮球，各种变卦，不给签字
8.工作氛围很压抑
9.喝水是大桶水抽水器，喝热水得用公司的祖传电水壶烧，没有饮水机，再早之前是烧自来水喝
10.各种白嫖加班，想过个清净周末很难，除了一句‘辛苦了’你啥也得不到
11.项目经理快被甲方同化了，越干越外行，昨天刚说的这么改，今天又全推翻再那样改
12.不允许私下沟通，所有交流都要在大群里说
13.画饼不管用了改威胁了，工资改为绩效形式，说别到时候扣了工资不知道因为啥

**Comment by GXiaoFeng** [comment]
去待了半个月，工资都没给

**Comment by ghost** [comment]
老板语录（欢迎各位补充）
1.你工作是给我干的么，是给公司干的么，是给你自己干的
2.虽然我有时候不在这里，但是谁认真工作，谁不认真工作我都知道
3.下班到点就走的人，这种人我绝不会让他存在公司
4.打卡是让你到楼下打的么，是你到楼上了屁股坐在凳子上才能打的

**Comment by fyb981030** [comment]
> 老板语录（欢迎各位补充）
> 1.你工作是给我干的么，是给公司干的么，是给你自己干的
> 2.虽然我有时候不在这里，但是谁认真工作，谁不认真工作我都知道
> 3.下班到点就走的人，这种人我绝不会让他存在公司
> 4.打卡是让你到楼下打的么，是你到楼上了屁股坐在凳子上才能打的

5.咱们到时候开个会，该惩罚惩罚，该表扬表扬（你倒是开啊）
6.现在公司招人都是会给上一家公司打电话问你这个人的口碑的，很多公司都实行了，咱公司也要实行
7.人家要自尊要面子的都努力表现自己，有些人啊，下班就走

**Comment by ghost** [comment]
公司群公告：
1、对你有严格要求的领导，才是能真正帮助你成长的好领导，使我痛苦者，必使我强大！ 

2、任何强大公司都不会给下属安全感，用最残忍方式激发每个人变得强大，自强不息！

3、凡是想办法给下属安全感的公司都会毁灭的，因为再强大的人，在温顺的环境中都会失去狼性！ 

4、凡是想方设法逼出员工能力，开发员工潜力的公司都会升腾不息，因为在这种环境下，要么变成狼，要么被狼吃掉!

5、最不给员工安全感的公司，其实给了真正的安全感，因为逼出了他们的强大，逼出了他们的成长，也因此他们有了未来！ 

6、如果真的爱你的下属，就考核他，要求他，高要求，高目标，高标准，逼迫他成长！ 

7、如果你碍于情面，低目标，低要求，低标准养了一群小绵羊、老油条，小白兔。这是对下属最大的不负责任! 对公司最大的不负责任！因为这只会助长他们的任性、嫉妒和懒惰和对工作对公司缺乏责任心。

8. 对公司、对工作有责任心的人就是对自己负责任，公司也会对你负责任。

没有企业的快速发展和高额利润，员工不可能获取丰厚的薪水。只有公司赚了钱，员工才可能获得较好的回报。从某种意义上讲，为公司赚钱就是为自己加薪。

**Comment by wukong001** [comment]
哈哈哈哈，这个老板语录，6啊

**Comment by GXiaoFeng** [comment]
> 公司群公告：
> 1、对你有严格要求的领导，才是能真正帮助你成长的好领导，使我痛苦者，必使我强大！
> 
> 2、任何强大公司都不会给下属安全感，用最残忍方式激发每个人变得强大，自强不息！
> 
> 3、凡是想办法给下属安全感的公司都会毁灭的，因为再强大的人，在温顺的环境中都会失去狼性！
> 
> 4、凡是想方设法逼出员工能力，开发员工潜力的公司都会升腾不息，因为在这种环境下，要么变成狼，要么被狼吃掉!
> 
> 5、最不给员工安全感的公司，其实给了真正的安全感，因为逼出了他们的强大，逼出了他们的成长，也因此他们有了未来！
> 
> 6、如果真的爱你的下属，就考核他，要求他，高要求，高目标，高标准，逼迫他成长！
> 
> 7、如果你碍于情面，低目标，低要求，低标准养了一群小绵羊、老油条，小白兔。这是对下属最大的不负责任! 对公司最大的不负责任！因为这只会助长他们的任性、嫉妒和懒惰和对工作对公司缺乏责任心。
> 
> 1. 对公司、对工作有责任心的人就是对自己负责任，公司也会对你负责任。
>    ```
>    没有企业的快速发展和高额利润，员工不可能获取丰厚的薪水。只有公司赚了钱，员工才可能获得较好的回报。从某种意义上讲，为公司赚钱就是为自己加薪。
>    ```

这饼画的可以

**Comment by MOONCOM** [comment]
> > 老板语录（欢迎各位补充）
> > 1.你工作是给我干的么，是给公司干的么，是给你自己干的
> > 2.虽然我有时候不在这里，但是谁认真工作，谁不认真工作我都知道
> > 3.下班到点就走的人，这种人我绝不会让他存在公司
> > 4.打卡是让你到楼下打的么，是你到楼上了屁股坐在凳子上才能打的
> 
> 5.咱们到时候开个会，该惩罚惩罚，该表扬表扬（你倒是开啊）
> 6.现在公司招人都是会给上一家公司打电话问你这个人的口碑的，很多公司都实行了，咱公司也要实行
> 7.人家要自尊要面子的都努力表现自己，有些人啊，下班就走

合着劳动法是不想让打工人体面啊

**Comment by fyb981030** [comment]
补充一下项目的事。大周末的发微信让你改东西，有时候老板还会在半夜11点多发微信问候。
对于项目，需求从来没有，只是给你说大体要个什么东西，至于什么需求，自己去网上找个差不多的做，一周做一个项目，做完之后就搁置了，一两个月不用，想起来就拿过来改吧改吧，给客户看完之后，开始无休止地改。这时候老板就会觉得，都做完了怎么又出问题了。
老板觉得，项目只要是做完了，就肯定不会出问题，一旦出了bug，你在日报上写今天改了什么项目的bug，就会说你，为什么你做的项目有bug，别人的就没有呢？我知道bug是不可避免的（之前跟她明确说过），但是人家有的人就能做到一个bug都没有，说到底还是你能力有问题。（真想说，没bug是因为没测……）
开了一次会，点名夸奖一个实习生，说工作认真负责，（其实电脑刷剧，玩游戏的时候她没看见，当时大家都想笑）夸奖有些人中午还去卫生间洗把脸，这种做法她很感动，她觉得是困了，洗把脸让自己清醒一下。还不提名地批评一些人（其实说的很明显）下班就走，（其实人家也就是下班之后半小时内走的）
日报写的少了嫌写三两句话，写的多了详细了，嫌写的啰嗦。说至于要写多少，自己看着估量
说发工资按照绩效发，什么项目奖金啊，年终奖啊都看禅道（一个用来管理项目，记录产品需求，提出bug的网站）上记录的工作，谁做了什么工作自己在禅道上记着，没写就当你没做，一切按照禅道来。
请个假，她自己看到的晚，非说你工作态度有问题，不管领导同没同意，提个请假就不管了，就不来上班了。谁请假还去找老板，经理同意了不就行了吗？真是要去找她，她会说你越级汇报，总之就是她有理
加班给买个泡面就觉得是对员工的恩惠，不过泡面也是就买了一次，从网上买了一箱，吃完再也没买。

**Comment by anzhongkai** [comment]
到点不下班？ 给钱吗？

**Comment by InMyLife888** [comment]
> 到点不下班？ 给钱吗？

不给

**Comment by ghost** [comment]
> 到点不下班？给钱吗？

给个嘚

**Comment by fchxqncj** [comment]
这公司领导太傻比了，我看了，都要气炸了，什么玩意儿

**Comment by a1542229460** [comment]
可能这就是老年人吧，老板时不时的在群里灌鸡汤：
老板越宽容，员工越没用！管理是就要淘汰人渣，激活人才！

2020-12-27




老板的宽容是一味害人的毒药

 

前两天在公司面试新人，正在看简历，对方是一名毕业半年的小女生。

 

简历还没看完呢，她就问我“伍经理，贵公司有什么福利吗？”

 

我简单的回答了他，每周有下午茶。

 

“那贵公司管理严格吗？”

 

我们公司老板管理还行吧，松弛有度，但是完不成目标或者达不到要求会收到处分。

 

她轻声“哦”了一声，但是她的眼神里写满了惊讶。

 

看完她的简历和她聊了会儿天以后我已经确定了今天的面试结果。

 

她刚毕业就去了一家初创公司工作，上下班都不用打卡，只要完成了自己的工作，想啥时候走都可以，她说老板人也炒鸡好，领导也炒鸡好，从来不找茬，上班一点压力都没有；每天都有下午茶，员工和领导和老板的关系就像哥们儿一样，公司没有刘经理陈主管，只有老刘和老陈，他们老板还说要把公司打造成中国上班最自由的公司....

 

后面的结果不同我说想必你们也猜到了，公司倒闭了，我也婉拒了她，因为面试中我问了她几个专业性的问题，发现她的能力根本达不到有半年一年经验的水平。

 

老板和领导的宽容就是一味害人的毒药，她在那家公司待的半年里除了长胖，能力和经验都没有得到成长，心态也完全和刚毕业的一样，也就是说她浪费了半年的时间在原地踏步。





老板越严厉，员工成长的越快

 

放下小姑娘的简历，看着她的背影消失，我想起了亲历的一件往事。

 

2010年大学刚毕业时，我和几个班上的同学一起合租；虽然住在一起但我们却没有在同一家公司上班，那时候刚出社会完全都是学生心态，每天下班大家回出租屋里最常干的一件事就是和同学抱怨自己的老板和领导，顺便吐槽公司。

 

奇哥是我们几个中间吐槽的最凶的一个，也是我们最同情的那个人，他有一个变态的上司和老板，他熬夜做出来的文案和PPT，经常被批的体无完肤，为了给客户呈现最好的方案，他经常加班加点，什么不会的东西都要现学，他说他们一整个公司都特别的变态，高压环境，高压任务，员工上班忙的喝水的时间都没有，每天像急着要投胎一样。

 

同学勇哥是我们最羡慕的一个人，工资都比我们的高，而且上司炒鸡好，对员工特别宽容，从来不找茬，出了什么错都是面色温和的讲清楚就行了，整个公司的氛围就像在养老，工作也清闲，朝九晚五。

 

两年后，奇哥从那家公司离职了，到了新公司工资立马翻了两番，从小组长变成了管十几个人团队的小主管，成为了我们几个同学里面成长速度最快的人，他说他很感谢那家变态的公司，不然他也不会成长那么快，人的潜力都是逼出来的。

 

而“养老式”上班的勇哥，工作两年却只涨了五百块钱工资，还是一个小职员，能力也没有多大的长进。

 

很多的年轻人找工作的目标就是要求公司工作压力要小，加班要少，氛围要轻松，其实是对自己的不负责任。

 

老天是很公平的，天上从没有白掉的馅饼，加班少，压力小对应的就是钱少，能力的成长速度慢，而压力大，上司严厉则对应着成长速度快，潜力得到激发，老板越严厉，员工成长的就越快。





管理者对员工的严厉就是最大的慈爱

 

老板的严厉从来就不是坏事，反而这是一种负责任的行为；温暖和谐的工作环境谁都想要，但是你来上班并不是来玩的，老板开一个公司也不是来做慈善的。



员工的能力成长速度对应着工资增长，但是人都是有惰性，没有人盯着催着员工就总想着停一停，坐一会儿休息会儿，老板越严厉，员工就越上进，成长的速度也就越快，披荆斩棘最终抵达梦想的远方。

 

古语有云，慈不带兵，义不养财，这个社会的法则就是弱肉强食，公司的生存和发展是老板考虑的最多的问题，过于仁慈心软，就带不出强兵，没有一支铁血的强兵公司怎么发展的好？最后公司倒了，员工也失业了，老板的严厉，最能够促进团队的发展，只要公司发展的好了，赚钱了，一切福利自然水涨船高，这就是老板对员工最大的“慈”。

**Comment by ghost** [comment]
说了小半年搬公司，终于搬了，搬到了高层次人才创业中心，周围很荒，连个吃早饭的地方都没，好像是zf有政策免3年房租。搬公司就叫了一辆小面包车，东西全靠我们搬，搬了半天一瓶水都没给买，也没聚个餐，连句辛苦了都没有.来的第二天早上网就坏了，老板开了个热点说先用她的，连连不上，再搜索就搜不到了

**Comment by a1542229460** [comment]
以试用期不合格为由辞退了一名员工，理由有二：1.拒绝周末无偿加班2.搬家不积极

**Comment by a1542229460** [comment]
周一去甲方那里开会接了个购物网站的项目，周二晚上原型图才做出来，周五要上线。老板说了：甲方要求周五上线，咱就周五上线

**Comment by fbu11** [comment]
> 员工的能力成长速度对应着工资增长，但是人都是有惰性，没有人盯着催着员工就总想着停一停，坐一会儿休息会儿，老板越严厉，员工就越上进，成长的速度也就越快，披荆斩棘最终抵达梦想的远方。

搁这儿写小作文呢？？？？？

**Comment by fyb981030** [comment]
顺便说一下，yu姓经理也挺不是人的。老板面前赤裸裸的一个舔狗，项目直接分给开发，老板问起来项目问题，经理基本上就会把开发人员也叫进办公室谈话，一旦老板想找事，经理就会舔着老板踩你。出来之后又开始说好话，说自己也没办法啥的，老阴阳人了。

**Comment by fyb981030** [comment]
深夜来自老板的问话
![12](https://user-images.githubusercontent.com/75299813/105322157-6db27000-5c03-11eb-9166-1af2852523a9.jpg)

**Comment by a1542229460** [comment]
现在不仅要每天写日报，还要写exelce表格计划，写今天要干什么，明天将要干什么，几号到几号完成，开会的时候再在会上讲解。光讨论怎么写这个计划就开了3次会
只要老板来公司了，必开会，分小组进去，每组时长0.5-2小时不等
下班了走人？不好意思先别走进来开个会

**Comment by acmenorbartender** [comment]
简单描述一下这个公司，老板是一个五十多岁的大妈性格跟你在菜市场遇到的大妈差不多吧。你要是问我这种人为啥能开公司，两个字“关系”，剩下的自己理解吧。大妈去抢菜时候有多扣她就有多扣吧：大妈买菜多要几个塑料袋，她公司喝水用的热水壶是一个盖子坏了一半的某银行的赠送的壶（没有饮水器）。大妈觉得去哪家菜铺子买菜是菜铺子老板的荣幸，她觉得公司来公司工作都是员工的荣幸，所以恶心员工的事一件不拉（并且觉得折磨员工是对员工成长好，可能是看鸡汤文看多了这个理解咱们父母辈经常在微信上看着推送）。因为她本质上觉得工作是员工的命根子我再恶心你们你们也不走。说白了就是管理60后工人的理念。我觉得来这个公司唯一的好处就是让你明白一个道理，只要有关系傻逼都能开公司，尽管上的项目bug成灾。如果你想问老板为啥关系怎么硬，建议面试看一下*娘半老，**犹存。

**Comment by ghost** [comment]
春节假期期间，一直给你打电话，让你晚上通宵搞项目，无偿

**Comment by a1542229460** [comment]
5点半下班，你6点走，说你工作不饱和。每天定的计划，不管中途有什么特殊情况（临时安排其他活，开会），加班加点也得今天弄完，开了几小时会晚上就晚走几小时

**Comment by lautherlee** [comment]
给讲讲“谁砸我的锅我砸谁的饭碗”的故事吧

**Comment by InMyLife888** [comment]
前两天是谁让给你讲讲砸了你的饭碗的故事？去问老板吧，你不是天天在老板旁边舔吗

**Comment by lautherlee** [comment]
发错人了吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月15日(星期四) 下午3:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [QingDaoIT/BlackList] 青岛中兴盛智能科技有限公司 (#98)





 
前两天是谁让给你讲讲砸了你的饭碗的故事？去问老板吧，你不是天天在老板旁边舔吗

**Comment by InMyLife888** [comment]
> 发错人了吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月15日(星期四) 下午3:36 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [QingDaoIT/BlackList] 青岛中兴盛智能科技有限公司 (#98) 前两天是谁让给你讲讲砸了你的饭碗的故事？去问老板吧，你不是天天在老板旁边舔吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

没发错，回复是所有人都能收到邮件的

**Comment by ypatdhpatd** [comment]
本楼层不定时更新
1.要求写日报，写的少了还不行，写的多了也不行。写的少了说你不干活，写的多了说你写废话。
2.职场pua+各种骚操作。首先领导不粘锅，老板会做出各种匪夷所思的操作，如果不出问题就是老板决策的好，如果出了问题就是我们的问题，基本上没有好决策。
3.老板不懂开发，不懂管理，什么都不懂。
4.项目经理熟练掌握了公司的生存法则，溜须拍马阴阳人。跟老板在一起的时候就各种甩锅，跟老板一路，只要一出办公室的门就开始卖惨，我也没办法，不这么办不行。现任项目经理别的不会，干这事是非常的优秀。
5.如果你要离职，项目经理会各种说这地方不好，我早想走了，老板什么都不懂，我过的特别难受，然后他转过头去跟老板说，这个人能力不行，干啥啥不会。
6.离职困难，30天是起步，只要你提了离职，就会有各种恶心的事情来刁难你。
7.只要到点走就会被喷。工作不是给我做的，是给你自己做的，这是在锻炼你，让你成长。你不是在糊弄我，是在糊弄你自己。
8.项目没有计划，全是看甲方心情，改动也全是甲方说了算。

**Comment by 576753961** [comment]
哈哈哈哈哈啊哈哈早知道这个公司了，我出来的时候IT黑名单上还没有，还好我怕的快 没遇到这些事事，我太幸运啦哈哈哈，辛苦了楼上老哥

**Comment by U-A-M** [comment]
1.项目经理是个伪君子，明里一套暗里一套，各种打小报告给你穿小鞋，不敲代码不干实事，每天的工作就是演戏，舔老板，每当老板来公司的时候，就赶紧起来找这个谈谈话装作认真工作的样子。
2.每天都要定计划就算了，也不知道项目经理是不是真不懂开发，正常定的很满的计划他砍工期，有的人定计划建一张表建一到三天的却不砍，旱的旱死，涝的涝死，有人一天一直在干活到最后还捞不着好，有人天天打游戏还啥事没有。
3.项目需求都还没确定，先定工期，就算你现在手头在忙别的项目，这个新项目你也不能耽误，还一直催你为啥不开始做，明知故问。项目干好了，功劳大半是他的，干不好，锅全是你的，提前给他说了这么短时间做不出来，他就甩一句加加班，最后加班也没做出来或者出点啥问题，就怼你做不完为什么不早说，锅甩的一干二净。
4.老板不懂开发，谁活干得好不好她不知道，全靠项目经理一张嘴，他很会揣测老板的心理，能听懂老板说的很nt的一些话并和老板继续交流，净捡一些老板喜欢听的话说，很多话一经他的嘴说出来就全变味了，可能这就是他整天不干实事还能一直过的这么滋润的原因吧，不得不说，也是本事

**Comment by woshiyuhui** [comment]
yh啊，你他娘的真是个天才啊，还整天搁这猜呢，天天当舔狗不累吗，好好做个人吧🐶

**Comment by JoinWebDev** [comment]
简单描述下公司现状吧:
1.老板不懂开发，胃口很大但是很抠，老画饼，想要马儿跑得快还想马儿不吃草，疯狂接项目，但是项目周期很短，普遍一到两周，客户加了需求开发周期也不变，只会让你加班做。公司很挣钱福利却很少。经常在群里发些毒鸡汤(可看楼上群公告)。加班到8:30订外卖报销，上限15(公司地方很偏，外卖很多都在20左右)，加班到10:30打车报销(9点左右就没公交了)。通宵啥也没有，周末去公司加班有调休。当你请假/调休的时候肯定会被说，例如现在这么忙，你还请假，好一手道德绑架
2十几个人的公司分了4级，总经理，项目经理/人事，小组长，普通员工，公司群光大群就有4个，一个公告群，一个技术群，还有脑干群，骨干群，各种小群不计其数。
3.每个人都要每天定计划，做什么，几号做到几号，是否完成，做成excel表格放在共享文件夹里，是否完成每天都要更新，如果某天因为开会或者临时安排了别的工作，今天的工作加班加点也得完成，开了几小时会晚上就得加几小时班补回来。
4.5:30下班，如果你走的早，会说你走这么早，工作肯定不饱和。
6再说说项目吧，没有书面合同确定需求，全靠客户一张嘴，如果客户那边换了对接的人，翻新重做都是堂有的事
7一共7个开发还给分了3个组，说各组做各组的项目，结果项目都很着急，一两个人一两周的时间根本做不完 ，经常借调人员先去忙别的项目，忙完了这个项目，之前耽搁的项目更急了
8.公司没有明确的调薪制度，涨工资都是部分员工偷着涨

**Comment by cnmlgb2021** [comment]
**人物介绍**：1：姓名：吴志扬。性别：男。出生日期：19980209。身份证号：371081199802099676 目前就职于：青岛绿苔数字科技有限公司（山东省青岛市崂山区科苑纬一路1号创新园G座18楼1801室）
职务：前端开发。学校：青岛职业技术学院:
                  2：姓名：薛秋风。性别：女。出生日期：19951106。身份证号：372928199511067920 目前就职于：智汇方象（青岛）软件有限公司(山东省青岛市崂山区科苑纬一路1号青岛国际创新园G座17楼)
职务：java后端开发。学校：青岛职业技术学院。
 
**事件分析**：1.这位吴先生，在公司期间因为试用期不过，对公司怀恨在心，然后作为键盘侠的他到处诽谤公司，开帖子骂公司。该帖子就是他开的，他的人品怎么样，大家可以到他的原单位去咨询，一副阴险小人的某样。给同事们留的印象极差，多位同事表示该人阴险。更可恶的是，他之前有个同学在公司就职，然后托他同学问项目经理公司需不需要人，经理说不需要后，他竟然在boss上偷偷的和公司老总联系。然后入职后，还装作不认识他的同学，呵呵了，这种不实诚的人在职场如何发展啊。另外不明白他死皮赖脸的想尽办法的来公司到底是处于什么目的。这种人太可怕。
                 2.这位薛女士更可怕，真是现实版的农夫与蛇，郭东先生与狼，公司就这一位女后端，她的技术大家自己想想吧烂得不着边际。做的几个系统，真的是够够的了，公司领导看她这样想让其转测试，征求过他的意见，她也同意了，谁知道她一直怀恨在心，本来是为了她好 ，谁曾想，她竟然这样。在公司还没离职的时候就一直在此处发帖子骂公司（可想她上班都干什么了）。然后提了离职了，你猜怎么着，竟然按照她的要求说几天走就几天走，测试的某项目一塌糊涂，测试的那叫一个烂，给公司留下了很多坑。而且走的时候还和大家热情告别，回头就开始在这上面骂开了。这上面的帖子一半都是她发的，还让她男朋友发帖子骂。有位同事说过一句话很经典，“”她这是对公司有多大的恨啊“，注册小号骂，隔三差五骂，栽赃陷害骂，道听途说骂，总之一句话就是她从原单位走就得骂原单位，骂她上司。青岛的公司注意一下这位薛女士吧。

最后大家找找共同点吧。这二位都是一个学校的，给学校真是丢尽了脸。另外目前他们入职的公司离的及其的近，估计没事就出来商量商量如何骂原单位，再次希望各位都能看清楚这二位的真正嘴脸。小人难防，大家注意！

**Comment by qaz2edc** [comment]
这家公司的项目经理是最难做的，身兼数职，想让你管理又想让你写代码。至今为止没有一个项目经理有好下场，无论刚开始多被信任和重用。
翻脸比翻书还快，在员工面前从来不给留面子，只要她觉得你做的有一点不好，不管在哪直接就是一顿狂怼。什么都是直接抛出来，至于怎么去做就是你自己的事了。一边要安抚老板，一边对接客户，另一边还要考虑员工，一不小心就被骂
奉劝各位慎重考虑
